### ISSUE TITLE
MIUI12.5有FC

### ISSUE THREAD

**Issue by dyt5AAUI** [TimeShining/Android-Dev-Tools#10]
java.lang.SecurityException: getSerial: The user 10372 does not meet the requirements to access device identifiers.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
	at android.os.Parcel.createException(Parcel.java:2360)
	at android.os.Parcel.readException(Parcel.java:2343)
	at android.os.Parcel.readException(Parcel.java:2285)
	at android.os.IDeviceIdentifiersPolicyService$Stub$Proxy.getSerialForPackage(IDeviceIdentifiersPolicyService.java:162)
	at android.os.Build.getSerial(Build.java:175)
	at O000000o.O00000Oo.O000000o.O00000o0.O0000o0o.O000O00o.O0000o00(SourceFile:280)
	at O000000o.O00000Oo.O00000o0.O0000o0o.O000O0OO.O00000o(SourceFile:590)
	at O000000o.O00000Oo.O00000o0.O0000o0o.O000O0OO.O000000o(SourceFile:70)
	at O000000o.O00000Oo.O00000o0.O0000o0o.O000O0OO$1.O00000Oo(SourceFile:79)
	at O000000o.O00000Oo.O00000o0.O0000Oo0.O000000o.O000000o(SourceFile:65)
	at O000000o.O00000Oo.O00000o0.O00000o0$14.O000000o(SourceFile:800)
	at O000000o.O00000Oo.O000000o.O00000o0.O000000o.O000000o$1.O000000o(SourceFile:33)
	at O000000o.O00000Oo.O000000o.O00000o0.O0000O0o.O000000o.onClick(SourceFile:38)
	at android.view.View.performClick(View.java:7509)
	at android.view.View.performClickInternal(View.java:7486)
	at android.view.View.access$3600(View.java:841)
	at android.view.View$PerformClick.run(View.java:28709)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8061)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.internal.telephony.TelephonyPermissions.reportAccessDeniedToReadIdentifiers(TelephonyPermissions.java:385)
	at com.android.internal.telephony.TelephonyPermissions.checkPrivilegedReadPermissionOrCarrierPrivilegePermission(TelephonyPermissions.java:327)
	at com.android.internal.telephony.TelephonyPermissions.checkCallingOrSelfReadDeviceIdentifiers(TelephonyPermissions.java:261)
	at com.android.internal.telephony.TelephonyPermissions.checkCallingOrSelfReadDeviceIdentifiers(TelephonyPermissions.java:237)
	at com.android.server.os.DeviceIdentifiersPolicyService$DeviceIdentifiersPolicy.getSerialForPackage(DeviceIdentifiersPolicyService.java:68)

**Comment by dyt5AAUI** [comment]
操作是获取设备ID或者是网络相关

**Comment by Trinea** [comment]
已修复，感谢反馈
