### ISSUE TITLE
Can't Create Directory

### ISSUE THREAD

**Issue by yoko-id** [TimeShining/Android-Dev-Tools#11]
![Screenshot_2021-03-13-18-35-14-091_com miui bugreport](https://user-images.githubusercontent.com/4809688/111028718-efb45d80-842a-11eb-9365-719b5e58420e.jpg)

g.d.a.exceptions.JadxRuntimeException: Can't create directory /storage/emulated/0/Trinea/DevTools/source/KPP PRATAMA PEKALONGAN-v1
	at O00000Oo.O00000Oo.O00000oo.O00000Oo.O00000Oo.O00000Oo(SourceFile:60)
	at O00000Oo.O00000Oo.O00000oo.O00000Oo.O00000Oo.O000000o(SourceFile:50)
	at O00000Oo.O00000Oo.O00000oo.O00000Oo.O00000Oo.O00000o0(SourceFile:112)
	at O00000Oo.O00000Oo.O00000Oo.O0000o00.O000000o(SourceFile:310)
	at O00000Oo.O00000Oo.O0000O0o.O0000o.O00000Oo(SourceFile:90)
	at O00000Oo.O00000Oo.O0000O0o.O0000o.O000000o(SourceFile:84)
	at O00000Oo.O00000Oo.O0000O0o.O0000o.O000000o(SourceFile:49)
	at O00000Oo.O00000Oo.O0000O0o.O0000o.run(SourceFile:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

**Comment by yoko-id** [comment]
![Uploading Screenshot_2021-03-13-18-36-59-456_com.android.settings.jpg…]()

**Comment by yoko-id** [comment]
![Screenshot_2021-03-13-18-36-51-715_com android settings](https://user-images.githubusercontent.com/4809688/111028745-22f6ec80-842b-11eb-80cf-cef1cface19b.jpg)
